name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code depuis le dépôt
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Installer les dépendances
    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r C:\Users\Manel CHENNA\Desktop\MLops\mlartifacts\321350530971794440\3b86390cb2fb4be2af11a49ffd34ec1c\artifacts\model\requirements.txt

    # 3. Exécuter les tests automatisés
    - name: Run Tests
      run: |
        source venv/bin/activate
        pytest

    # 4. Construire l'image Docker
    - name: Build Docker Image
      run: docker build -t ml-app:latest .

    # 5. Déployer l'image Docker en local (ou sur un serveur distant)
    - name: Deploy Docker Container
      run: docker run -d -p 5000:5000 --name ml-app-container ml-app:latest

    # 6. Nettoyer les anciens conteneurs (optionnel)
    - name: Clean Up
      if: always()
      run: docker rm -f ml-app-container || true
