name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code depuis le dépôt
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Installer les dépendances
    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 3. Démarrer l'API en arrière-plan
    - name: Start API
      run: |
        source venv/bin/activate
        python main.py &
        sleep 10  # Attendre 10 secondes pour que le serveur démarre correctement

    # 4. Exécuter les tests automatisés
    - name: Run Tests
      run: |
        source venv/bin/activate
        pytest

    # 5. Construire l'image Docker
    - name: Build Docker Image
      run: docker build -t ml-app:latest .

    # 6. Déployer l'image Docker en local (ou sur un serveur distant)
    - name: Deploy Docker Container
      run: docker run -d -p 5000:5000 --name ml-app-container ml-app:latest

    # 7. Nettoyer les anciens conteneurs (optionnel)
    - name: Clean Up
      if: always()
      run: docker rm -f ml-app-container || true
